server:
  port: 8001
spring:
  application:
    name: cloud-provider-hystix-payment
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
eureka:
  client:
    #表示不向注册中心注册自己
    register-with-eureka: true
    #是否从eurekaServer中抓取已注册的信息，默认为true，单机无所谓 集群必须为true 才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: payment8001
    #访问路径可以显示IP
    prefer-ip-address: true
    #Eureka服务的最后一次收到心跳后等待时间上限，默认90s,超时将剔除服务
    lease-expiration-duration-in-seconds: 2
    #Eureka客户端向服务的发送心跳的间隔时间，默认30秒
    lease-renewal-interval-in-seconds: 1

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.cctang.springcloud.entities